default:
	$(MAKE) -C "/home/pi/MEME4925Project/module/MQ7" && \
	$(MAKE) -C "/home/pi/MEME4925Project/module/DHT22" && \
	$(MAKE) -C "/home/pi/MEME4925Project/module/HW_508" && \
	$(MAKE) -C "/home/pi/MEME4925Project/module/White_LED" 

clean:
	$(MAKE) -C "/home/pi/MEME4925Project/module/MQ7" clean && \
	$(MAKE) -C "/home/pi/MEME4925Project/module/DHT22" clean && \
	$(MAKE) -C "/home/pi/MEME4925Project/module/HW_508" clean && \
	$(MAKE) -C "/home/pi/MEME4925Project/module/White_LED" clean

